clc;
clear all;
close all;

fs=1000;

path = {'D:\sp_cup\Grid_A\Power_recordings\Train_Grid_A_P1.wav'...
        'D:\sp_cup\Grid_A\Power_recordings\Train_Grid_A_P2.wav'...
        'D:\sp_cup\Grid_A\Power_recordings\Train_Grid_A_P3.wav'...
        'D:\sp_cup\Grid_A\Power_recordings\Train_Grid_A_P4.wav'...
        'D:\sp_cup\Grid_A\Power_recordings\Train_Grid_A_P5.wav'...
        'D:\sp_cup\Grid_A\Power_recordings\Train_Grid_A_P6.wav'...
        'D:\sp_cup\Grid_A\Power_recordings\Train_Grid_A_P7.wav'...
        'D:\sp_cup\Grid_A\Power_recordings\Train_Grid_A_P8.wav'...
        'D:\sp_cup\Grid_A\Power_recordings\Train_Grid_A_P9.wav'...
        ...
        'D:\sp_cup\Grid_B\Power_recordings\Train_Grid_B_P1.wav'...
        'D:\sp_cup\Grid_B\Power_recordings\Train_Grid_B_P2.wav'...
        'D:\sp_cup\Grid_B\Power_recordings\Train_Grid_B_P3.wav'...
        'D:\sp_cup\Grid_B\Power_recordings\Train_Grid_B_P4.wav'...
        'D:\sp_cup\Grid_B\Power_recordings\Train_Grid_B_P5.wav'...
        'D:\sp_cup\Grid_B\Power_recordings\Train_Grid_B_P6.wav'...
        'D:\sp_cup\Grid_B\Power_recordings\Train_Grid_B_P7.wav'...
        'D:\sp_cup\Grid_B\Power_recordings\Train_Grid_B_P8.wav'...
        'D:\sp_cup\Grid_B\Power_recordings\Train_Grid_B_P9.wav'...
        'D:\sp_cup\Grid_B\Power_recordings\Train_Grid_B_P10.wav'...
        ...
        'D:\sp_cup\Grid_C\Power_recordings\Train_Grid_C_P1.wav'...
        'D:\sp_cup\Grid_C\Power_recordings\Train_Grid_C_P2.wav'...
        'D:\sp_cup\Grid_C\Power_recordings\Train_Grid_C_P3.wav'...
        'D:\sp_cup\Grid_C\Power_recordings\Train_Grid_C_P4.wav'...
        'D:\sp_cup\Grid_C\Power_recordings\Train_Grid_C_P5.wav'...
        'D:\sp_cup\Grid_C\Power_recordings\Train_Grid_C_P6.wav'...
        'D:\sp_cup\Grid_C\Power_recordings\Train_Grid_C_P7.wav'...
        'D:\sp_cup\Grid_C\Power_recordings\Train_Grid_C_P8.wav'...
        'D:\sp_cup\Grid_C\Power_recordings\Train_Grid_C_P9.wav'...
        'D:\sp_cup\Grid_C\Power_recordings\Train_Grid_C_P10.wav'...
        'D:\sp_cup\Grid_C\Power_recordings\Train_Grid_C_P11.wav'...
        ...
        'D:\sp_cup\Grid_D\Power_recordings\Train_Grid_D_P1.wav'...
        'D:\sp_cup\Grid_D\Power_recordings\Train_Grid_D_P2.wav'...
        'D:\sp_cup\Grid_D\Power_recordings\Train_Grid_D_P3.wav'...
        'D:\sp_cup\Grid_D\Power_recordings\Train_Grid_D_P4.wav'...
        'D:\sp_cup\Grid_D\Power_recordings\Train_Grid_D_P5.wav'...
        'D:\sp_cup\Grid_D\Power_recordings\Train_Grid_D_P6.wav'...
        'D:\sp_cup\Grid_D\Power_recordings\Train_Grid_D_P7.wav'...
        'D:\sp_cup\Grid_D\Power_recordings\Train_Grid_D_P8.wav'...
        'D:\sp_cup\Grid_D\Power_recordings\Train_Grid_D_P9.wav'...
        'D:\sp_cup\Grid_D\Power_recordings\Train_Grid_D_P10.wav'...
        'D:\sp_cup\Grid_D\Power_recordings\Train_Grid_D_P11.wav'...
        ...
        'D:\sp_cup\Grid_E\Power_recordings\Train_Grid_E_P1.wav'...
        'D:\sp_cup\Grid_E\Power_recordings\Train_Grid_E_P2.wav'...
        'D:\sp_cup\Grid_E\Power_recordings\Train_Grid_E_P3.wav'...
        'D:\sp_cup\Grid_E\Power_recordings\Train_Grid_E_P4.wav'...
        'D:\sp_cup\Grid_E\Power_recordings\Train_Grid_E_P5.wav'...
        'D:\sp_cup\Grid_E\Power_recordings\Train_Grid_E_P6.wav'...
        'D:\sp_cup\Grid_E\Power_recordings\Train_Grid_E_P7.wav'...
        'D:\sp_cup\Grid_E\Power_recordings\Train_Grid_E_P8.wav'...
        'D:\sp_cup\Grid_E\Power_recordings\Train_Grid_E_P9.wav'...
        'D:\sp_cup\Grid_E\Power_recordings\Train_Grid_E_P10.wav'...
        'D:\sp_cup\Grid_E\Power_recordings\Train_Grid_E_P11.wav'...
        ...
        'D:\sp_cup\Grid_F\Power_recordings\Train_Grid_F_P1.wav'...
        'D:\sp_cup\Grid_F\Power_recordings\Train_Grid_F_P2.wav'...
        'D:\sp_cup\Grid_F\Power_recordings\Train_Grid_F_P3.wav'...
        'D:\sp_cup\Grid_F\Power_recordings\Train_Grid_F_P4.wav'...
        'D:\sp_cup\Grid_F\Power_recordings\Train_Grid_F_P5.wav'...
        'D:\sp_cup\Grid_F\Power_recordings\Train_Grid_F_P6.wav'...
        'D:\sp_cup\Grid_F\Power_recordings\Train_Grid_F_P7.wav'...
        'D:\sp_cup\Grid_F\Power_recordings\Train_Grid_F_P8.wav'...
        ...
        'D:\sp_cup\Grid_G\Power_recordings\Train_Grid_G_P1.wav'...
        'D:\sp_cup\Grid_G\Power_recordings\Train_Grid_G_P2.wav'...
        'D:\sp_cup\Grid_G\Power_recordings\Train_Grid_G_P3.wav'...
        'D:\sp_cup\Grid_G\Power_recordings\Train_Grid_G_P4.wav'...
        'D:\sp_cup\Grid_G\Power_recordings\Train_Grid_G_P5.wav'...
        'D:\sp_cup\Grid_G\Power_recordings\Train_Grid_G_P6.wav'...
        'D:\sp_cup\Grid_G\Power_recordings\Train_Grid_G_P7.wav'...
        'D:\sp_cup\Grid_G\Power_recordings\Train_Grid_G_P8.wav'...
        'D:\sp_cup\Grid_G\Power_recordings\Train_Grid_G_P9.wav'...
        'D:\sp_cup\Grid_G\Power_recordings\Train_Grid_G_P10.wav'...
        'D:\sp_cup\Grid_G\Power_recordings\Train_Grid_G_P11.wav'...
        ...
        'D:\sp_cup\Grid_H\Power_recordings\Train_Grid_H_P1.wav'...
        'D:\sp_cup\Grid_H\Power_recordings\Train_Grid_H_P2.wav'...
        'D:\sp_cup\Grid_H\Power_recordings\Train_Grid_H_P3.wav'...
        'D:\sp_cup\Grid_H\Power_recordings\Train_Grid_H_P4.wav'...
        'D:\sp_cup\Grid_H\Power_recordings\Train_Grid_H_P5.wav'...
        'D:\sp_cup\Grid_H\Power_recordings\Train_Grid_H_P6.wav'...
        'D:\sp_cup\Grid_H\Power_recordings\Train_Grid_H_P7.wav'...
        'D:\sp_cup\Grid_H\Power_recordings\Train_Grid_H_P8.wav'...
        'D:\sp_cup\Grid_H\Power_recordings\Train_Grid_H_P9.wav'...
        'D:\sp_cup\Grid_H\Power_recordings\Train_Grid_H_P10.wav'...
        'D:\sp_cup\Grid_H\Power_recordings\Train_Grid_H_P11.wav'...
        ...
        'D:\sp_cup\Grid_I\Power_recordings\Train_Grid_I_P1.wav'...
        'D:\sp_cup\Grid_I\Power_recordings\Train_Grid_I_P2.wav'...
        'D:\sp_cup\Grid_I\Power_recordings\Train_Grid_I_P3.wav'...
        'D:\sp_cup\Grid_I\Power_recordings\Train_Grid_I_P4.wav'...
        'D:\sp_cup\Grid_I\Power_recordings\Train_Grid_I_P5.wav'...
        'D:\sp_cup\Grid_I\Power_recordings\Train_Grid_I_P6.wav'...
        'D:\sp_cup\Grid_I\Power_recordings\Train_Grid_I_P7.wav'...
        'D:\sp_cup\Grid_I\Power_recordings\Train_Grid_I_P8.wav'...
        'D:\sp_cup\Grid_I\Power_recordings\Train_Grid_I_P9.wav'...
        'D:\sp_cup\Grid_I\Power_recordings\Train_Grid_I_P10.wav'...
        'D:\sp_cup\Grid_I\Power_recordings\Train_Grid_I_P11.wav' };
    
    files = {'AP1','AP2','AP3','AP4','AP5','AP6','AP7','AP8','AP9',...
             'BP1','BP2','BP3','BP4','BP5','BP6','BP7','BP8','BP9','BP10',...
             'CP1','CP2','CP3','CP4','CP5','CP6','CP7','CP8','CP9','CP10','CP11'...
             'DP1','DP2','DP3','DP4','DP5','DP6','DP7','DP8','DP9','DP10','DP11'...
             'EP1','EP2','EP3','EP4','EP5','EP6','EP7','EP8','EP9','EP10','E11'...
             'FP1','FP2','FP3','FP4','FP5','FP6','FP7','FP8'...
             'GP1','GP2','GP3','GP4','GP5','GP6','GP7','GP8','GP9','GP10','GP11'...
             'HP1','HP2','HP3','HP4','HP5','HP6','HP7','HP8','HP9','HP10','HP11'...
             'IP1','IP2','IP3','IP4','IP5','IP6','IP7','IP8','IP9','IP10','IP11'};
         
    grid = [1*ones(1,9) 2*ones(1,10) 3*ones(1,11) ...  %keeping a record of the
            4*ones(1,11) 5*ones(1,11) 6*ones(1,8) ...  %grid of the corresponding
            7*ones(1,11) 8*ones(1,11) 9*ones(1,11) ]';  %path

        
    len = length(path);
    
    
 %%   
for jl = 1:len
    
    fprintf('loading data from ....\n%s\n',char(path(jl)));
    fprintf('recording no.  ---> %d\n',jl);
    
    
    %%listing features
    var_x = [];
    mean_x = [];
    skew_x = [];
    kurt_x = [];
    diff_x = [];
    wav_coef = [];
    global_mean = [];
    global_var = [];
    
    pp=1; %initialization for wav_coef loop
    
    
    
    Y=wavread(char(path(jl)));
    % Y1=decimate(Y',2);

    Y_f=filter(Bandpass_n,Y');

    F=[];
    for i=1:((length(Y)/400)-1)
        p=Y_f(200*(i-1)+1:200*(i-1)+400);
        p1=fft(p,4096);
        f = (0:length(p1)-1)*1000/length(p1);
        [~,m]=max(log(abs(p1).^2));
        alpha=20*log(abs(p1(m-1)));
        beta=20*log(abs(p1(m)));
        lambda=20*log(abs(p1(m+1)));
        m1=.5*(alpha-lambda)*(f(m+1)-f(m))/(alpha-2*beta+lambda); % for quadratic interpolation
        f(m)=f(m)+m1;
        F=[F f(m)];
    end
   % plot(F)
    x = F;

    %% Statistical feature
    mn = mean(x);
    vr = var(x);
    
%     global_mean = [global_mean mn];
%     global_var = [global_var vr];
    

    for i = 32:32:(length(x)-32)        %window length 32 samples
        
        global_mean = [global_mean mn]; %replicating global mean and variance for each training data row
        global_var = [global_var vr];
    
        m = mean(x(i:i+31));        %taking mean of 32 samples at a time
        mean_x = [mean_x m];        %appending window mean to matrix

        v = var(x(i:i+31));         %taking variance of 32 samples at a time

        var_x = [var_x v];          %appending window variance to matrix

    end

    
    for i = 32:32:(length(x)-32)        %window length 32 samples 

        d_m = abs(diff(x(i:i+31))); %make a difference matrix

        d1 = sort(d_m,'descend');
        
        d = (d1(1)+d1(2)+d1(3))/3;           %taking mean of max 3 differences

        diff_x = [diff_x d];

    end


    %% Wavelet based features

    F1=F/max(F);                         %normalize ENF
   
   feature_per_rcrd = 0;
   D=[];
   wav_mean=[];
   wav_var=[];
   AR=ar(F,2);     %2nd order Autoregressive model
   AR_coef=AR.a(2:3);
   
    for i = 32:32:(length(F)-32)

       temp1= F(i:i+31);
       temp2=F1(i:i+31);                  % for normalized ENF

       [C, L]=wavedec(temp1,5,'haar');

       [C1, L1]=wavedec(temp2,5,'haar');      % for normalized ENF

        wav_coef(:,pp)=C;
        
        A5= wrcoef('a',C,L,'haar',5);             % approximation
        D(:,1)=wrcoef('d',C,L,'haar',1);          % detail_signal_1
        D(:,2)=wrcoef('d',C,L,'haar',2);          % detail_signal_2
        D(:,3)=wrcoef('d',C,L,'haar',3);          %detail_signal_3
        D(:,4)=wrcoef('d',C,L,'haar',4);          % detail_signal_4
        D(:,5)=wrcoef('d',C,L,'haar',5);          % detail_signal_5
        wav_mean=mean(A5);                        % mean of approximation
        wav_var=var(A5);                          %variance of approximation
        for i=1:5
            wav_mean=[wav_mean mean(D(:,i))];     % mean of detail
            wav_var=[wav_var var(D(:,i))];        % variance of detail
        end
        wavcoef_n(:,pp)=C1;
        pp=pp+1;
        feature_per_rcrd = feature_per_rcrd + 1;

    end

    responsevar = grid(jl)*ones(1,feature_per_rcrd);
    
    %%arranging training dataset 
    
%     master_trainer = [ var_x' mean_x' diff_x' ...
%                     wav_coef' global_mean' global_var' ];
master_trainer = [ var_x' mean_x' diff_x' ...
                     AR_coef' wav_mean'  wav_var global_mean' global_var' ];

    responsevar = responsevar';
    save(char(files(jl)),'master_trainer','responsevar');
end

